amp: true
anomaly_clean: true
batch_size: 32
cuda: true
data_type: molecule
epochs: 1024
freeze_layers: null
freeze_layers_reversed: false
kfold: 5
learning_rate: 0.0001
load_model_dir: null
logger_level: 1
max_epochs: 100
max_norm: 5.0
metrics: mse
model_name: unimolv1
model_size: 84m
num_classes: 7
patience: 5
remove_hs: false
seed: 42
smi_strict: true
smiles_col: SMILES
split: random
split_group_col: scaffold
split_method: 5fold_random
split_seed: 42
target_col_prefix: property_
target_cols: property_CpG_Abs,property_LPS_Abs,property_LPS_Lum,property_MPLA_Abs,property_MPLA_Lum,property_cGAMP_Abs,property_cGAMP_Lum
target_normalize: none
task: multilabel_regression
use_amp: true
use_cuda: true
warmup_ratio: 0.03
